### ISSUE TITLE
Clean UP & Dockerization eos2lm8

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos2lm8#5] opened 2023-07-03 06:23 UTC

**Comment by pittmanriley** [comment] 2023-07-06 05:54
Hi @GemmaTuron, when I was testing the model prior to refactoring, I had trouble fetching the model on my computer due to Mac issues again. I tried fetching from the repo path, from GitHub, etc. but they didn't work. So, I tried using codespaces and was able to fetch the model there. However, the model works on some inputs in the test/inputs folder, but for others, it shows an index error. This is the same error as I'm getting with the eml_canonical.csv file with eos7ack. Here's the error when I use the compound_single.csv file as input. Again, this is within codespaces: 

```
Traceback (most recent call last):
  File "/root/miniconda3/bin/ersilia", line 33, in <module>
    sys.exit(load_entry_point('ersilia', 'console_scripts', 'ersilia')())
  File "/root/miniconda3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/bentoml/cli/click_utils.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/bentoml/cli/click_utils.py", line 115, in wrapper
    return_value = func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/bentoml/cli/click_utils.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/ersilia/ersilia/cli/commands/run.py", line 36, in run
    for result in mdl.run(input=input, output=output, batch_size=batch_size):
  File "/ersilia/ersilia/core/model.py", line 194, in _api_runner_iter
    for result in api.post(input=input, output=output, batch_size=batch_size):
  File "/ersilia/ersilia/serve/api.py", line 319, in post
    for res in self.post_unique_input(
  File "/ersilia/ersilia/serve/api.py", line 293, in post_unique_input
    for res in self.post_only_calculations(input, output, batch_size):
  File "/ersilia/ersilia/serve/api.py", line 138, in post_only_calculations
    result = json.loads(self._post(input, output))
  File "/ersilia/ersilia/serve/api.py", line 95, in _post
    result = self._do_post(input, output)
  File "/ersilia/ersilia/serve/api.py", line 84, in _do_post
    result_ = self.output_adapter.refactor_response(result_)
  File "/ersilia/ersilia/io/output.py", line 122, in refactor_response
    m = self._nullify_meta(m, r)
  File "/ersilia/ersilia/io/output.py", line 108, in _nullify_meta
    one_output = random.choice(result)
  File "/root/miniconda3/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
```

I know the error points me to output.py, api.py, etc., but I don't think these files really help me identify where the root cause of the error is occurring. Do you have any ideas of how I could resolve this?

**Comment by GemmaTuron** [comment] 2023-07-06 06:27
Hi @pittmanriley 
What is the compounds_single.csv file you mention?
what is the length of the files that gives you errors?
Please modify the code adding print statements so that we can see if it gets stuck at particular molecules, or particular indexes. Also, please add the whole Log of the error as an attachment to all your issues.

**Comment by pittmanriley** [comment] 2023-07-06 14:14
Hi @GemmaTuron, the compound_single.csv file is the test input file in the ersilia/test/inputs folder. It looks like this: 

```
smiles
CC1C2C(CC3(C=CC(=O)C(=C3C2OC1=O)C)C)O
```

I'm noticing that the only inputs that fail are ones with a single smiles sample. If I do `ersilia run -i "COc1ccc2c(NC(=O)Nc3cccc(C(F)(F)F)n3)ccnc2c1"`, for example, then it will cause the same index error. I'll use print statements and go through the code to get a sense of why this is happening. Here is the out.log of the error: 
[out.log](https://github.com/ersilia-os/eos2lm8/files/11969048/out.log)

**Comment by GemmaTuron** [comment] 2023-07-07 06:56
Is the modle in Colab giving the same issue? to understand if is a system related or a model related thing

**Comment by pittmanriley** [comment] 2023-07-07 07:11
@GemmaTuron I just tested it in Colab with only the first smiles in the eml_canonical file and the same index error occurred.

**Comment by GemmaTuron** [comment] 2023-07-10 09:40
I have tried this model and the fetching works fine, but when running predictions I get the following:

`ersilia -v api -i "CCCOCCCNC"`

```
Traceback (most recent call last):
  File "/home/gturon/anaconda3/envs/ersilia/bin/ersilia", line 33, in <module>
    sys.exit(load_entry_point('ersilia', 'console_scripts', 'ersilia')())
  File "/home/gturon/anaconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/gturon/anaconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/gturon/anaconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gturon/anaconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gturon/anaconda3/envs/ersilia/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/gturon/anaconda3/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "/home/gturon/anaconda3/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 115, in wrapper
    return_value = func(*args, **kwargs)
  File "/home/gturon/anaconda3/envs/ersilia/lib/python3.7/site-packages/bentoml/cli/click_utils.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/gturon/github/ersilia-os/ersilia/ersilia/cli/commands/api.py", line 42, in api
    api_name=api_name, input=input, output=output, batch_size=batch_size
  File "/home/gturon/github/ersilia-os/ersilia/ersilia/core/model.py", line 194, in _api_runner_iter
    for result in api.post(input=input, output=output, batch_size=batch_size):
  File "/home/gturon/github/ersilia-os/ersilia/ersilia/serve/api.py", line 320, in post
    input=unique_input, output=None, batch_size=batch_size
  File "/home/gturon/github/ersilia-os/ersilia/ersilia/serve/api.py", line 293, in post_unique_input
    for res in self.post_only_calculations(input, output, batch_size):
  File "/home/gturon/github/ersilia-os/ersilia/ersilia/serve/api.py", line 138, in post_only_calculations
    result = json.loads(self._post(input, output))
  File "/home/gturon/github/ersilia-os/ersilia/ersilia/serve/api.py", line 95, in _post
    result = self._do_post(input, output)
  File "/home/gturon/github/ersilia-os/ersilia/ersilia/serve/api.py", line 84, in _do_post
    result_ = self.output_adapter.refactor_response(result_)
  File "/home/gturon/github/ersilia-os/ersilia/ersilia/io/output.py", line 122, in refactor_response
    m = self._nullify_meta(m, r)
  File "/home/gturon/github/ersilia-os/ersilia/ersilia/io/output.py", line 108, in _nullify_meta
    one_output = random.choice(result)
  File "/home/gturon/anaconda3/envs/ersilia/lib/python3.7/random.py", line 261, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```
@miquelduranfrigola can you check?

**Comment by GemmaTuron** [comment] 2023-07-11 09:41
> Hi @GemmaTuron, the compound_single.csv file is the test input file in the ersilia/test/inputs folder. It looks like this:
> 
> ```
> smiles
> CC1C2C(CC3(C=CC(=O)C(=C3C2OC1=O)C)C)O
> ```
> 
> I'm noticing that the only inputs that fail are ones with a single smiles sample. If I do `ersilia run -i "COc1ccc2c(NC(=O)Nc3cccc(C(F)(F)F)n3)ccnc2c1"`, for example, then it will cause the same index error. I'll use print statements and go through the code to get a sense of why this is happening. Here is the out.log of the error: [out.log](https://github.com/ersilia-os/eos2lm8/files/11969048/out.log)

@pittmanriley 

Do you have an update on this? did you try the printing of the outputs to find out what is the empty output?

**Comment by GemmaTuron** [comment] 2023-07-11 09:59
@pittmanriley 

I am trying this model. The api available is both predict and run - make sure only run remains
```
🚀 Serving model eos2lm8: smiles-transformer

   URL: http://127.0.0.1:33517
   PID: 961548
   SRV: conda

👉 To run model:
   - run

   These APIs are also valid:
   - predict

💁 Information:
   - info
```

**Comment by GemmaTuron** [comment] 2023-07-11 11:13
If you go onto the service.py, you'll see it is counting the output file has a header, which, as you can read in predict.py, is not true:
```
with open(infile, "r") as f:
    reader = csv.reader(f)
    next(reader)
    smiles = []
    for r in reader:
        smiles += [r[0]]

x_split = [split(sm) for sm in smiles]
xid, xseg = get_array(x_split)
X = trfm.encode(torch.t(xid))

np.savetxt(outfile, X, delimiter=",")
```

This line `h = next(reader) `needs to be removed so that it does not discard the first molecule as header (hence, when only one molecule is passed, it fails, whereas if you pass 10 molecules you'll get preds for 9).

**Comment by pittmanriley** [comment] 2023-07-13 03:58
Hi @GemmaTuron, I spent a good amount of time today trying to understand the error I'm getting at fetch time for this model. It's a 'ModuleNotFound' error, and here's the log: 
[out.log](https://github.com/ersilia-os/eos2lm8/files/12035202/out.log)

This is the same error that shows up in the actions after I submitted the PR. In the main.py file, there's the following line on line 24: `from pretrain_trfm import TrfmSeq2seq`. The pretrain_trfm.py file is within the smiles_transformer folder, and I've checked the path that is being created on line 23 is correct: `sys.path.append(os.path.join(root, "smiles_transformer"))`. The path is correct, and when the model fetches, it is unable to find the pretrain_trfm.py file for some reason. I'm not sure why this is happening. 

I've tried importing the module in different ways, but nothing I did seemed to work. There are a couple more imports below the pretrain_trfm one, and I believe the same error will happen for those modules as well.

**Comment by GemmaTuron** [comment] 2023-07-13 06:19
Hi @pittmanriley 

A few questions:
- What command are you using to get this results? Are you fetching from repo_path, from github?
- Was the model working before refactoring?
- Can you print and show here the path to be sure its correct?
- Can you try to activate the conda env eos2lm8 and then run the code snippet from the same location to import the pretrain_trfm?
- Have you tried manually creating a conda env and installing all the packages, then running the .sh file directly?

When I tested this model, I did not find this issue so I'm sure is just a small bug, please share also the different import options you have tried!

**Comment by pittmanriley** [comment] 2023-07-13 06:46
Hi @GemmaTuron

- The command I've been using to test in CLI is `ersilia -v fetch eos2lm8 --repo_path /Users/rileypittman/eos2lm8/` and within codespaces is `ersilia -v fetch eos2lm8 --repo_path /workspaces/ersilia/eos2lm8/`. These commands get me the module error, and doing the --from_github command does not work for me in CLI or Codespaces. Here's the log for the --from_github command: 
[out.log](https://github.com/ersilia-os/eos2lm8/files/12036111/out.log)

- The model did work for me, but only within Codespaces. When I run it in codespaces, I use `ersilia -v fetch eos2lm8`
- When I run it in CLI, the path that is produced is this: `/Users/rileypittman/eos/repository/eos2lm8/20230712182527_87639C/eos2lm8/artifacts/framework/code/smiles_transformer`. This is the correct path to the smiles_transformer folder. 
- I'm not sure what you mean by run the code snippet from the same location. Do you mean just activate the eos2lm8 environment and fetch as I have been? 
- I tried manually installing all the packages and running the run.sh file, but this didn't work either. It says it couldn't find the pretrain_trfm module again

I deleted the different options I tried, but I researched this issue and found that it could have to do with importing it incorrectly. So, I tried adding an __init__.py file to the framework folder to make it a package, and that didn't work so I also tried adding that file to the smiles_transformer folder, but that didn't work either. I also tried adjusting the path to include a "/" at the end of it, but this made no difference. Lastly, I tried importing by writing out the whole path, like this: `from eos2lm8.model.framework.smiles_transformer.pretrain_trfm import TrfmSeq2seq`, but I couldn't get this to work either. 


When you got it to work, how did you fetch it? What was the command you used?

**Comment by GemmaTuron** [comment] 2023-07-13 07:08
Hi @pittmanriley 

When fetching from github it seems you have a git lfs error:
```
Hook already exists: post-commit

        #!/bin/bash

        # This is a custom git hook installed for codespaces when you'll be unable to push your changes to the source repository.
        # Instead, we'll fork the repo on your behalf, ensure you have appropriate permissions, and transfer the codespace to that fork.

        trap "mv $0 $0.codespaces-disabled" EXIT

        echo "You don't have write access to the $GITHUB_REPOSITORY repository, so you cannot push changes to it."
        echo "To obtain write access we will point this codespace at your fork of $GITHUB_REPOSITORY, creating that fork if it doesn't exist."
        echo

        if [ -t 1 ]; then
        read -p "Would you like to proceed? " -n 1 -r < /dev/tty
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]
        then
        exit 0
        fi
        fi

        URL="https://api.github.com/vscs_internal/user/$GITHUB_USER/codespaces/$CODESPACE_NAME/fork_repo"


        current_branch=$(git rev-parse --abbrev-ref HEAD)

        response=$(curl -s -w "%{http_code}" -X POST -H "Authorization: token $GITHUB_TOKEN" -d "{\"branch\":\"$current_branch\"}" $URL)

        # Grab the last line which is the status code
        http_cod
```

**Comment by GemmaTuron** [comment] 2023-07-13 07:09
first try this out and test the original code. Try fetching again and see if this error is still appearing.
make sure to do `git lfs install` on the command line before

**Comment by GemmaTuron** [comment] 2023-07-13 16:18
@pittmanriley 

The path is not well specified:
From what I see in your repository, you want to go into `framework/smiles_transformer` you are still inside `code`

**Comment by GemmaTuron** [comment] 2023-07-15 15:58
@pittmanriley 

If the latest change worked open a PR when ready!

**Comment by pittmanriley** [comment] 2023-07-17 06:23
Hi @GemmaTuron, I remember submitting a PR sometime last week, and I received a notification saying that you merged it into main. Is this correct?

**Comment by GemmaTuron** [comment] 2023-07-17 06:53
thanks, I forgot to update the status of the model to reviewed in the project.

**Closed as completed** 2023-07-18 17:11 UTC
